# Generated by Django 3.2.4 on 2022-05-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='women',
            name='like',
            field=models.IntegerField(default=0, verbose_name='Лайки'),
        ),
    ]
