# Generated by Django 4.0.4 on 2022-06-06 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0002_women_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('content', models.TextField(blank=True, verbose_name='Текст коментария')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время публикации')),
                ('like', models.IntegerField(default=0, verbose_name='Лайки')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='women.women', verbose_name='Пост')),
            ],
        ),
    ]
